# Layt Lar Mal မှ အခမဲ့ ပညာဒါန အနေဖြင့် youtube မှာ မျှဝေနေသည့် **'Pandas Data Structure များ မိတ်ဆက်ခြင်း'** ဗီဒီယိုမှ ဖြစ်သည်။

ဒီ လေ့ကျင့်ခန်းများကို Wes McKinney ၏ **Python for Data Analysis : Data Wrangling with pandas, NumPy & Jupyter** ဆိုသည့် စာအုပ်မှာ ကောက်နှုတ်ဖော်ပြသည်။

---

# 💙 Support our work


ကျွန်တော်တို့ရဲ့ ဒီ video လေးက အနည်းငယ်ဖြစ်ဖြစ် အကူညီဖြစ်တယ်ဆိုရင် ကျွန်တော်တို့အား အောက်ပါ နည်းလမ်းများဖြင့် support ပေးနိုင်ပါသည်။ so

👉 **Video Link:** [youtube.com/watch?v=7Wi1vPWLe9E&feature=youtu.be](LINK_HERE)

:

---

### 🌟 Become a Member
Get **full access** to all our learning materials in:
- 📊 **Data Analysis**
- 🤖 **Machine Learning**
- 🧠 **Deep Learning**
- 📈 **Data Science Projects & Tutorials**

👉 **Join here:** [Mehttps://www.facebook.com/story.php?story_fbid=862582666283864&id=100075964145979&mibextid=wwXIfr&rdid=Ex5YjWTXhFO2jTEl#Link](LINK_HERE)

---

### ☕ Buy Me a Coffee
Your support helps us continue creating **free, high-quality educational content**.

👉 **Support usbuymeacoffee.com/zinmin)pe a Coffee](LINK_HERE)

---

### 👍 Like · Subscribe · Share
Help us grow by supportinchannels:

- ▶️ www.youtube.com/@laytlarmal 
- UTUBE_LINK)
- �https://www.facebook.com/laytlarmal** [Facebook Page](FACEBOOK_LINK)

Every like, share, and subscription truly means a lot 💫

---

**Thank you for being part of our learning community! 🚀**

# Video 2: Pandas Data Structures များ မိတ်ဆက်ခြင်း

## 0. Pandas import လုပ်ခြင်း

`pip install pandas` ဖြင့် install လုပ်ပြီးနောက်

`pd` အတိုကောက်နဲ့ import တယ်။

In [ ]:
import pandas as pd

## 1. Pandas မှာ ပါသည့် Data Structure များ

Pandas ရဲ့ အဓိက **data structure** 

    - Series
    - DataFrame

ဒီ 2 ခုက pandas တင်မဟုတ်ပဲ python မှာ data analysis လုပ်မယ်ဆို မဖြစ်မနေ သိရမယ့် အရာဖြစ်ပြီး data နဲ့ ပတ်သတ်တဲ့ အလုပ်တွေ တော်တော်များများကို ဖြေရှင်းလို့ ရတယ်။

### 1.1 Series 
Column တစ်ခုသာ ရှိတဲ့ Data Structure မျိုး

. 
NumPy အနေနဲ့ ကြည့်မယ်ဆိုရင်တော့ 1-D Array (Vector

. data တစ်ခုချင်းစီမှာ label တွေ ရှိတယ် --> index လို့ ခေါ်တယ်။ 

. list တို့ tuple တို့စတဲ့ sequence data မျိုးတွေကနေ အလွယ်တကူ ဖန်တီးနိုင်တယ်။်။

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

ဘယ်ဘက်က တန်ဖိုးတွေက index (နေရာ) ဖြစ်ပြီး ညာဘက်က တန်ဖိုးတွေက သက်ဆိုင်ရာ value တွေ ဖြစ်တယ်။
index တွေကို မသတ်မှတ်ထားရင် default အနေနဲ့ 0 ကနေ 1, 2, 3 အစဉ်လိုက် သတ်မှတ်ပြီးသားဖြစ်တယ်။

`array` attribute ကို သုံးပြီး အပေါ်မှာ ပြုလုပ်ထားတဲ့ Series ထဲက values(တန်ဖိုး)တွေပဲ ထုတ်လို့ ရသလို `index` attribute ကို သုံးပြီး index တွေကို ထုတ်လို့ ရတယ်။

In [4]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

`.array` attribute ကို သုံးပြီး ကြည့်ရင် pandas ရဲ့ array တွေက NumPy array တွေကို အမှီပြုထားတာ တွေ့ရတယ်။

တစ်ခါတစ်လေ data တစ်ခုချင်းစီကို default index မဟုတ်ပဲ သပ်သပ် label လေးတွေ ပေးချင်တယ်။ (NumPy မှာ မရ)

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

ဒါကြောင့် NumPy မှာလို မဟုတ်ပဲ အဲ့ label တွေကို index အနေနဲ့ သုံးပြီး တန်ဖိုးတွေကို ဆွဲထုတ်လို့ ရတယ်။

In [9]:
obj2["a"]

-5

In [10]:
obj2["d"] = 6

In [11]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

ဒီမှာ ["c", "a", "d"] က index တွေ စုထားတဲ့ list ဖြစ်တယ်။

NumPy function တွေ ဒါမှမဟုတ် NumPy ပုံစံ operationတွေ လုပ်လို့ ရတယ်။ ဥပမာ Boolean array ကို သုံးပြီး filtering လုပ်တာမျိုး၊ ပြီးတော့ scalar multiplication, math function တွေ သုံးခြင်း

In [17]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [18]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Series ကို index : value အတွဲလိုက် ဖြစ်နေတဲ့ fixed-length, ordered dictionary ကနေလည်း ပြုလုပ်လို့ ရတယ်။

--> Series ကို dictionary ကနေ ပြုလုပ်လို့ ရတယ်။

In [21]:
"b" in obj2

True

In [22]:
"e" in obj2

False

In [23]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Series ကနေ dictionary ကိုလည်း အလွယ်တကူ ပြန်ပြောင်းလို့ ရတယ်။

In [24]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

dictionary ကနေ လုပ်တဲ့ အခါ, index တွေက dictionary’s key တွေရဲ့ အစီအစဉ်အတိုင်းဖြစ်တယ်။ အဲ့ index တွေကို သပ်သပ် သက်မှတ်ခြင်းဖြင့် order တွေကို ပြောင်းလို့ ရတယ်။

In [25]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

sdata ထဲမှာ ရှိတဲ့ index တွေနဲ့ ညီနေတာ ၃ ခု ရှိတယ်။ "California" ဆိုတဲ့ တစ်ခု မရှိဘူး။ အဲ့လို တန်ဖိုးတွေ မရှိရင် pandas က သူ့ကို ပျောက်နေတဲ့ တန်ဖိုး **missing**value သို့မဟုတ် **NA** value တွေလို့ သတ်မှတ်ပြီး **NaN (Not a Number)** ဆိုပြီး ပြတယ်။
"Utah" ကတော့ states ထဲမှာ မပါဝင်နေလို့ result အသစ်မှာ မပါလာဘူး။


အဲ့လို missing data တွေကို ဒီ playlist မှာ “missing,” “NA,” or “null” ဆိုပြီးတော့ ခေါ်ဝေါ်သွားမယ်။

In [26]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Series မှာ ဒီဟာတွေကို instance method အနေနဲ့လည်း ပါရှိတယ်။

In [28]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

missing data တွေ ကိုင်တွယ်တာနဲ့ ပတ်သတ်ပြီး နောက်ပိုင်းမှာ အသေးစိတ် ပြောမယ်။

Series တွေရဲ့ ကောင်းတာတစ်ခုက တွက်ချက်တာတွေ တစ်ခုခု လုပ်မယ်ဆို index label တွေ အချင်းချင်း auto align (ညှိ) ပေးလိုက်တာပဲ။

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Data alignment features နဲ့ ပတ်သတ်ပြီး နောက်မှ အသေးစိတ် ပြောမယ်။ databases မှာဆို join operation နဲ့ တူတယ်။

Series object ကိုယ်တိုင်ကော သူ့ရဲ့ index ကော `name` attribute ရှိပြီး တခြား pandas functionality တွေနဲ့ တွဲသုံးလို့ ရတယ်။

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Series’s index တွေကို assignment လုပ်ခြင်းဖြင့် ပြောင်းလဲလို့ ရတယ်။

In [35]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [36]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 1.2 DataFrame
- Row နဲ့ Column တွေ ပါတဲ့ Table (Spreadsheet) ပုံစံ Data Structure မျိုး
- NumPy အနေနဲ့ ကြည့်မယ်ဆိုရင်တော့ 2-D Array (Matrix) ပေါ့
- index တွေတူတဲ့ Series(Columns) တွေ စုထားတဲ့ Table လို့ ပြောလို့ရတယ်
- DataFrame မှာ ကျတော့ row ကော column ကော index တွေ ရှိတ်။ ယ်။

Note: DataFrame က တည်ဆောက်ပုံအားဖြင့် 2-D ဆိုပေမယ့် hierarchical indexing သဘောတရားကို သုံးပြီး higher-dimensional table ပုံစံတွေ ဆောက်လို့ ရတယ်။

DataFrame တွေ ပြုလုပ်လို့ ရတဲ့ နည်းလမ်း အမျိုးမျိုး ရှိတယ်။ အသုံးအများဆုံးကတော့ အရွယ်အစားတူညီတဲ့ list သို့မဟုတ် NumPy array တွေနဲ့ ဖွဲ့စည်းထားတဲ့ dictionary ကနေ ပြုလုပ်ခြင်းဖြစ်တယ်။

In [37]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [38]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

ရလာတဲ့ DataFrame က index တွေဟာ Series တွေတုန်းကအတိုင်းပဲ အလိုအလျောက် သတ်မှတ်ပြီးသားဖြစ်မယ်။
column တွေကလည်း data(dictionary) မှာပါတဲ့ keys အစဉ်အတိုင်း သတ်မှတ်ပြီးသားဖြစ်မယ်။

note : Jupyter သုံးရင် pandas DataFrame object တွေကို ပို လှလှပပ ပြပေးတယ်။

အရွယ်အစား ကြီးမားတဲ့ DataFrame တွေအတွက်  `head` method ကို သုံးပြီး ပထမ ငါး row ပဲ ဆွဲထုတ်လို့ ရတယ်။

In [39]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

အလားတူ `tail` ကို သုံးပြီး နောက်ဆုံး ငါး row ဆွဲထုတ်လို့ ရတယ်။

In [40]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

column တွေကို DataFrame ပြုလုပ်စဉ်မှာ သတ်မှတ်ပေးရင် သတ်မှတ်ပေးတဲ့အတိုင်း ရမယ်။

In [41]:
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

dictionary ထဲမှာ မပါတဲ့ column ကို ထည့်ထားရင် အဲ့ column အတွက် တန်ဖိုးတွေအကုန် missing
value အနေနဲ့ ပြမယ်။

In [42]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [45]:
frame2.index

RangeIndex(start=0, stop=6, step=1)

In [43]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

DataFrame ထဲက column တွေကို Series မှာလိုပဲ dictionary-like
notation သို့မဟုတ် dot attribute notation ဖြင့် ရယူနိုင်တယ်။

In [47]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [48]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

Note:
- frame2[column] လို သုံးရင် ဘယ် column နဲ့ပဲ ဖြစ်ဖြစ် သုံးလို့ ရတယ်။ 
- ဒါပေမယ့် frame2.column မှာဆို column နာမည်တွေက DataFrame မှာပါတဲ့ အခြား method, attribute နာမည်တွေနဲ့ တူနေရင် မရဘူး။

ရလာတဲ့ column (Series) က DataFrame တစ်ခုလုံးရဲ့ index နဲ့ အတူတူပဲ၊ name
attribute လည်း သတ်မှတ်ပြီးသားဖြစ်တယ်။

Row တွေကို special attribute တွေဖြစ်တဲ့ `iloc` နဲ့ `loc` ကိုသုံးပြီး **position** သို့မဟုတ် **name** နဲ့ ဆွဲထုတ်နိုင်တယ်။`loc` နဲ့ `iloc` ကို သုံးပြီး selection လုပ်ခြင်းကို နောက်ကျ အသေးစိတ် ပြောမယ်။

In [51]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [52]:
# locate (by row name)
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [53]:
# index locate (by position)
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

Column တွေကို assignment(=) ဖြင့် ပြင်လို့ ရတယ်။ ဥပမာ လွတ်နေတဲ့ debt column ကို scalar value (ကိန်းဂဏန်း ၁ လုံး) သို့မဟုတ် array of values (ကိန်းအစုအဝေး) ဖြင့် ပြင်လို့ ရတယ်။

In [54]:
frame2["debt"] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [55]:
frame2["debt"] = np.arange(6.)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

Series တစ်ခုခုနဲ့ assign လုပ်တဲ့ အခါမှာတော့ သူ့ရဲ့ index label က DataFrame ရဲ့ index နဲ့ ညှိသွားမှာ ဖြစ်ပြီး သက်ဆိုင်ရာ index မှာ တန်ဖိုးတွေ မရှိပါက missing value တွေနဲ့ ဖြည့်သွားမှာ ဖြစ်တယ်။

In [56]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
frame2["debt"] = val
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

မရှိတဲ့ column တစ်ခုခုကို Assign ရင်တော့ အဲ့ column နာမည်နဲ့ column အသစ်တစ်ခု ပြုလုပ်မှာ ဖြစ်တယ်။

In [57]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

Note: frame2.eastern dot attribute notation ကို သုံးပြီးတော့ column အသစ် ပြုလုပ်လို့ မရပါ။

`del` keyword ကို သုံးပြီး dictionary မှာလို column တွေကို ဖျက်လို့ ရတယ်။ ဥပမာ - အပေါ်က "Ohio" ဖြစ်ရင် True မဟုတ်ရင် False လုပ်ထားတဲ့ Boolean တန်ဖိုးတွေပါတဲ့ eastern column ကို ဖျက်မယ်။

In [58]:
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

Note:

DataFrame ကို indexing လုပ်ခြင်းဖြင့် ရလာတဲ့ column က view သဘောတရားဖြစ်ပြီး copy မဟုတ်ပါ။ ဆိုလိုတာက ရလာတဲ့ Series အပေါ်မှာ ပြုလုပ်လိုက်တဲ့ ပြောင်းလဲမှုတွေက မူလ DataFrame မှာပါ သက်ရောက်မှာ ဖြစ်တယ်။ သပ်သပ်စီ ခွဲထုတ်ချင်တာဆိုရင်တော့ Series ရဲ့ `copy` method ကို သုံးလို့ ရပါတယ်။

dictionary ကနေ DataFrame ပြုလုပ်တဲ့ နောက် အသုံးများ နည်းလမ်းတစ်ခုကတော့ **nested dictionary** အသုံးပြုခြင်းဖြစ်တယ်။

In [59]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

DataFrame ပြုလုပ်တဲ့ အခါ nested dictionary ကို သုံးရင် pandas က အပြင်ဘက် dictionary key တွေကို column index တွေ အဖြစ် အတွင်းဘက် dictionary key တွေကိုတော့ row index တွေ အဖြစ် သတ်မှတ်သွားမှာပါ။

In [60]:
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

NumPy array တွေမှာလို `T` attribute ကို သုံးပြီး DataFrame ကို transpose (row နဲ့ column လဲခြင်း) ပြုလုပ်လို့ ရတယ်။

In [61]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

Note: 

column တွေထဲ ပါတဲ့ data တွေရဲ့ type တွေက မတူညီကြရင် transpose လုပ်ခြင်းက column တွေရဲ့ data type တွေကို discard လုပ်လိုက်မှာ ဖြစ်တယ်။ ဒါကြောင့် transpose လုပ်ပြီး နောက်တစ်ခေါက် transpose ပြန်လုပ်ပါက ရှေ့မှာ ရှိခဲ့တဲ့ type နဲ့ ပတ်သတ်တဲ့ information ပျောက်သွားနိုင်ပါတယ်။ အဲ့လိုမျိုးဆို column ရဲ့ type က ရိုးရိုး python object အနေနဲ့ ရှိနေမှာ ဖြစ်တယ်။

inner dictionarie တွေရဲ့ key တွေ ပေါင်းစပ်သွားပြီး ရလာတဲ့ DataFrame ရဲ့ index ဖြစ်ငွားမှာ ဖြစ်ပါတယ်။ ဒါပေမယ့် index ကို  explicitly သတ်မှတ်ထားရင်တော့ အဲ့လို ဖြစ်လာမှာ မဟုတ်ပါ။

In [62]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

Series တွေကို ပေါင်းစပ်ထားတဲ့ Dictionaries တွေလည်း အဲ့လိုပဲ။

In [63]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

DataFrame ထဲထည့်ပြီး ပြုလုပ်လို့ ရတဲ့ အရာတွေကို အောက်မှာ တွေ့နိုင်ပါတယ်။

Table 5-1. Possible Data Inputs to the `DataFrame` Constructor

| **Type** | **Notes** |
|---------|-----------|
| 2D `ndarray` | A matrix of data, passing optional row and column labels |
| Dictionary of arrays, lists, or tuples | Each sequence becomes a column in the DataFrame; all sequences must be the same length |
| NumPy structured / record array | Treated as the *dictionary of arrays* case |
| Dictionary of `Series` | Each value becomes a column; indexes from each Series are unioned together to form the result’s row index if no explicit index is passed |
| Dictionary of dictionaries | Each inner dictionary becomes a column; keys are unioned to form the row index as in the *dictionary of Series* case |
| List of dictionaries or `Series` | Each item becomes a row in the DataFrame; unions of dictionary keys or Series indexes become the DataFrame’s column labels |
| List of lists or tuples | Treated as the *2D ndarray* case |
| Another `DataFrame` | The DataFrame’s indexes are used unless different ones are passed |
| NumPy `MaskedArray` | Like the *2D ndarray* case, except masked values are missing in the DataFrame result |aFrame result

DataFrame ရဲ့ index နဲ့ column တွေကို name attribute တွေ သတ်မှတ်ထားတယ်ဆိုရင် သူတို့ကိုလည်း ပြမှာ ဖြစ်တယ်။

In [64]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

Series နဲ့ မတူတာက DataFrame တစ်ခုလုံးကိုတော့ name attribute သတ်မှတ်လို့ မရပါ။ DataFrame ရဲ့ `to_numpy` method ကို သုံးပြီး DataFrame ထဲက တန်ဖိုးတွေကြီးပဲကို two-dimensional ndarray အနေနဲ့ ထုတ်လို့ ရတယ်။

In [65]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

DataFrame’s column တွေက တစ်ခုနဲ့ တစ်ခု type မတူရင် column အားလုံးကို ချုံပြီး သက်ရောက်နိုင်တဲ့ data type ကို အလိုအလျောက် ရွေးချယ်ခံရမှာ ဖြစ်တယ်။

In [66]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 1.3 Index Objects 

axis တွေရဲ့ label (Data‐Frame’s column names တွေပါဝင်) တွေနဲ့ အခြား metadata (axis name or names) တွေကို Index object က တာဝန်ယူထားပါတယ်။

Series သို့မဟုတ် DataFrame ပြုလုပ်လိုက်တဲ့ အချိန်မှာ ရှိနေတဲ့ column index, row index တွေဟာ Index ဆိုတဲ့ object  အနေနဲ့ ပြောင်းလဲသွားခြင်းဖြစ်တယ်။

In [67]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index = obj.index

In [68]:
index

Index(['a', 'b', 'c'], dtype='object')

In [69]:
index[1:]

Index(['b', 'c'], dtype='object')

Index object တွေဟာ immutable ဖြစ်ပြီး user က တခြား တန်ဖိုးနှင့် ပြောင်းလဲမရနိုင်ပါ။ tuple လိုမျိုးပေါ့။

In [70]:
index[1] = "d" # TypeError

TypeError: Index does not support mutable operations

Data တွေ ပေါင်းစပ်တဲ့အခါမှာ ပိုပြီး စိတ်ချရစေတယ်။ Index တွေက fix တွေ ဖြစ်နေတယ်။

In [71]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

In [73]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [74]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [75]:
obj2.index is labels

True

Note:

တချို့သူတွေက Index ရဲ့ အစွမ်းကို ကောင်းကောင်း အသုံးမချနိုင်ကြဘူး။ တချို့ result တွေမှာ indexed data တွေကလည်း အရေးကြီးပြီး သူတို့ကို နားလည်ဖို့ကလည်း အရေးကြီးတယ်။

သူတို့တွေက array တွေနဲ့ ဆင်တူတာအပြင် **fixed-size set** လိုမျိုးလည်း စွမ်းဆောင်ကြတယ်။

In [77]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [78]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [79]:
"Ohio" in frame3.columns

True

In [80]:
2003 in frame3.index

False

python ရဲ့ မူလ set နဲ့ မတူတာတစ်ခုက pandas Index တွေဟာ ထပ်နေတဲ့ label တွေလည်း ဖြစ်နိုင်တယ်။

In [81]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

label တွေ တူနေတဲ့ အရာတွေကို select လုပ်ရင် အဲ့ label နဲ့ သက်ဆိုင်တဲ့ တန်ဖိုး အကုန်လုံးကို ပေးမှာ ဖြစ်တယ်။

Index တစ်ခုချင်းစီက set logic တွေကို ပုံဖော်တဲ့ method နဲ့ properties(attributes) တွေ ရှိကြပြီး သူ့မှာ ပါဝင်တဲ့ data တွေနဲ့ ပတ်သတ်ကြတယ်။ အချို့ အသုံးများတဲ့ အရာတွေက အောက်ပါအတိုင်း ဖြစ်ကြတယ်။


| **Method / Property** | **Description** |
|----------------------|-----------------|
| `append()` | Concatenate with additional `Index` objects, producing a new `Index` |
| `difference()` | Compute set difference as an `Index` |
| `intersection()` | Compute set intersection |
| `union()` | Compute set union |
| `isin()` | Compute Boolean array indicating whether each value is contained in the passed collection |
| `delete()` | Compute new `Index` with element at index *i* deleted |
| `drop()` | Compute new `Index` by deleting passed values |
| `insert()` | Compute new `Index` by inserting element at index *i* |
| `is_monotonic` | Returns `True` if each element is greater than or equal to the previous element |
| `is_unique` | Returns `True` if the `Index` has no duplicate values |
| `unique()` | Compute the array of unique values in the `Index` |