# Layt Lar Mal မှ အခမဲ့ ပညာဒါန အနေဖြင့် youtube မှာ မျှဝေထားသည့် **'Pandas အခြေခံ လုပ်ဆောင်ချက်များ'** ဗီဒီယိုမှ ဖြစ်သည်။

ဒီ လေ့ကျင့်ခန်းများကို Wes McKinney ၏ **Python for Data Analysis : Data Wrangling with pandas, NumPy & Jupyter** ဆိုသည့် စာအုပ်မှာ ကောက်နှုတ်ဖော်ပြသည်။

---

# 💙 Support our work


ကျွန်တော်တို့ရဲ့ ဒီ video လေးက အနည်းငယ်ဖြစ်ဖြစ် အကူညီဖြစ်တယ်ဆိုရင် ကျွန်တော်တို့အား အောက်ပါ နည်းလမ်းများဖြင့် support ပေးနိုင်ပါသည်။ so

👉 **Video Link:** [https://youtu.be/1Q-KDLKG814?si=_-oRl2dvRzXNO4hs]

:

---

### 🌟 Become a Member
Get **full access** to all our learning materials in:
- 📊 **Data Analysis**
- 🤖 **Machine Learning**
- 🧠 **Deep Learning**
- 📈 **Data Science Projects & Tutorials**

👉 **Join here:** [https://www.facebook.com/story.php?story_fbid=862582666283864&id=100075964145979&mibextid=wwXIfr&rdid=Ex5YjWTXhFO2jTEl]

---

### ☕ Buy Me a Coffee
Your support helps us continue creating **free, high-quality educational content**.

👉 **Support usbuymeacoffee.com/zinmin)pe a Coffee]

---

### 👍 Like · Subscribe · Share
Help us grow by supportinchannels:

- ▶️ **Youtube Link:** www.youtube.com/@laytlarmal 
- **Facebook Page:** https://www.facebook.com/laytlarmal**

Every like, share, and subscription truly means a lot 💫

---

**Thank you for being part of our learning community! 🚀**

# Essential Functionality (Pandas ရဲ့ အခြေခံလုပ်ဆောင်ချက်များ)

သည် video မှာ Series နဲ့ DataFrame နဲ့ ပတ်သတ်ပြီး data များနှင့် အပြန်အလှန်လုပ်ဆောင်ရာတွင် အသုံးပြုရမယ့် အခြေခံအကျဆုံး နည်းလမ်းများကို လေ့လာသွားမည် ဖြစ်ပါတယ်။ နောက်ဗီဒီယိုတွေမှာတော့ pandas ကိုအသုံးပြုပြီး data analysis နဲ့ data များကိုင်တွယ်ခြင်း (manipulation) ဆိုင်ရာ အကြောင်းအရာတွေကို ပိုပြီး အတွင်းကျကျ လေ့လာသွားမှာ ဖြစ်ပါတယ်။ 
သည် ဗီဒီယိုကတော့ pandas library တစ်ခုလုံးကို အသေးစိတ်မှတ်တမ်း (documentation) တင်ဖို့ ရည်ရွယ်ထားခြင်းမဟုတ်ဘဲ အသုံးအများဆုံး feature များကိုသာ အဓိကထားဖော်ပြပေးမှာ ဖြစ်ပါတယ်။ သိပ်ပြီးအသုံးမများသော အကြောင်းအရာတွေကိုတော့ pandas ရဲ့ online documentation မှာ ထပ်မံဖတ်ရှုနိုင်ပါတယ်။

In [1]:
import pandas as pd
import numpy as np

# 1. Reindexing (Index ပြန်လည်သတ်မှတ်ခြင်း)

## 1.1 Series များတွင် Reindex လုပ်ခြင်း

In [2]:
# Series တစ်ခုကို index သတ်မှတ်ပြီး တည်ဆောက်ခြင်း
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

Time series လိုမျိုး အစဉ်လိုက်ရှိတဲ့ data တွေကို reindex လုပ်သည့်အခါ တန်ဖိုးတွေကို ဖြည့်စွက်ခြင်း (interpolation/filling) ပြုလုပ်လိုနိုင်တယ်။ `method` option ကို အသုံးပြုပြီး လုပ်ဆောင်နိုင်ပြီး `ffill` (forward-fill) ကတော့ ပျောက်နေတဲ့ တန်ဖိုးတွေကို ရှေ့မှာရှိတဲ့ တန်ဖိုးကို ယူပြီး ဆက်တိုက်ဖြည့်ပေးသွားမည် ဖြစ်တယ်။

In [4]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [5]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [6]:
# method="ffill" ကိုသုံးပြီး ကွက်လပ်များကို ရှေ့တန်ဖိုးဖြင့် ဖြည့်ခြင်း
obj3.reindex(np.arange(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [7]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

## 1.2 DataFrame များတွင် Reindex လုပ်ခြင်း

In [8]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [9]:
# Row index များကို reindex လုပ်ခြင်း
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [10]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [11]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [12]:
frame.reindex(states, axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [13]:
frame.reindex(states, axis=1)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### reindex function ၏ အဓိက argument များ

| Argument | Description |
| :--- | :--- |
| **labels** | index အဖြစ် အသုံးပြုမည့် sequence အသစ် ဖြစ်သည်။ |
| **index** | index (rows) အသစ်အဖြစ် အသုံးပြုမည့် sequence ဖြစ်သည်။ |
| **columns** | column label အသစ်အဖြစ် အသုံးပြုမည့် sequence ဖြစ်သည်။ |
| **axis** | reindex လုပ်မည့် axis ကို သတ်မှတ်သည်။ "index" (rows) သို့မဟုတ် "columns" ဖြစ်နိုင်သည်။ |
| **method** | အချက်အလက်ဖြည့်စွက်သည့်နည်းလမ်း (Interpolation method) ဖြစ်သည်။ "ffill" (forward) သို့မဟုတ် "bfill" (backward) ဖြစ်နိုင်သည်။ |
| **fill_value** | reindex လုပ်စဉ် data မရှိသောနေရာများတွင် အစားထိုးမည့် တန်ဖိုးဖြစ်သည်။ |

`loc` operatorကို အသုံးပြုပြီးလည်း reindex လုပ်နိုင်တယ်။ သည်နည်းလမ်းက index label အသစ်တွေ အကုန်လုံးက DataFrame အတွင်းထဲ ရှိနေမှသာ အလုပ်လုပ်မှာ ဖြစ်တယ်။

In [14]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [15]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

In [16]:
frame.loc[["a", "d", "c", "asdfs"], ["California", "Texas"]]

KeyError: "['asdfs'] not in index"

# 2. Dropping Entries from an Axis (data များ ဖျက်ခြင်း)

## 2.1 Dropping Entries from Series

In [17]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [18]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [19]:
# "d" နှင့် "c" နှစ်ခုလုံးကို ဖယ်ရှားခြင်း
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [20]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

## 2.2 Dropping Entries from DataFrame

In [21]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [22]:
# Row များကို ပယ်ဖျက်ခြင်း
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [25]:
# Column တစ်ခုကို ပယ်ဖျက်ခြင်း
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [32]:
data.drop(["Ohio"], axis=1)

KeyError: "['Ohio'] not found in axis"

# 3. Indexing, Selection, နှင့် Filtering

## 3.1 Series တွင် Indexing လုပ်ခြင်း

Series indexing (`obj[...]`) က NumPy array indexing နဲ့ ဆင်တူပေမယ့်လည်း integer(location) များအပြင် Series ရဲ့ index label တွေကိုပါ အသုံးပြုနိုင်ခြင်းမှာ ကွာခြားချက်ဖြစ်တယ်။

In [33]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [34]:
obj["b"]

np.float64(1.0)

In [35]:
obj[1]

C:\Users\zinmi\AppData\Local\Temp\ipykernel_106100\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

np.float64(1.0)

In [36]:
# Slicing လုပ်ခြင်း
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [37]:
obj["b":"d"]

b    1.0
c    2.0
d    3.0
dtype: float64

In [38]:
# Label စာရင်းဖြင့် ရွေးချယ်ခြင်း
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [39]:
# Position စာရင်းဖြင့် ရွေးချယ်ခြင်း
obj[[1, 3]]

C:\Users\zinmi\AppData\Local\Temp\ipykernel_106100\2218300471.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [40]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [41]:
obj < 2

a     True
b     True
c    False
d    False
dtype: bool

In [42]:
# Boolean array ဖြင့် filter လုပ်ခြင်း --> Boolean Filtering (Masking)
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

### `loc` နှင့် `iloc` အော်ပရေတာများ

Label တွေ သုံးပြီး data indexing လုပ်ရင် အပေါ်ကလိုမျိုး indexing မဟုတ်ပဲ သီးသန့်လုပ်ထားတဲ့ `loc` operator ကို အသုံးပြုဖို့ ပိုပြီးအကြံပြုတယ်။ အဲ့လို operator မျိုး သုံးခြင်းဖြင့် indexing လုပ်ရာမှာ integer တွေကို label အဖြစ် သတ်မှတ်ခြင်း နဲ့ position အဖြစ် သတ်မှတ်ခြင်းတို့မှာ ဖြစ်ပေါ်တတ်တဲ့ ရှုပ်ထွေးမှုတွေကို ရှောင်ရှားနိုင်မှာ ဖြစ်ပါတယ်။

In [44]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [43]:
obj.loc["b"]

np.float64(1.0)

In [45]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

အကယ်၍ index မှာ integer တွေ ပါဝင်နေပါက `[]` သုံးပြီး indexing လုပ်ခြင်းက label နှင့် position ကြားမှာ ရှုပ်ထွေးနိုင်တယ်။ ထို့ကြောင့် position အခြေပြု indexing အတွက် `iloc` ကို အသုံးပြုသင့်တယ်။

In [46]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [49]:
obj1

2    1
0    2
1    3
dtype: int64

In [48]:
obj2

a    1
b    2
c    3
dtype: int64

In [50]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [52]:
obj1.loc[2]

np.int64(1)

> **သတိပြုရန်:** Label များနဲ့ slicing လုပ်ရာမှာ (Python ရဲ့ ပုံမှန် slicing နဲ့မတူဘဲ) အဆုံးသတ် point (endpoint) သည် inclusive ဖြစ်တယ် (ဆိုလိုသည်မှာ အဆုံးသတ် label ပါ ပါဝင်တယ်)။

In [53]:
obj2

a    1
b    2
c    3
dtype: int64

In [54]:
# Label slicing (endpoint inclusive ဖြစ်သည်)
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [55]:
# တန်ဖိုးများကို ပြောင်းလဲသတ်မှတ်ခြင်း
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

### 3.2 DataFrame တွင် Indexing လုပ်ခြင်း

DataFrame မှာ index လုပ်ခြင်းကတော့ column တစ်ခု သို့မဟုတ် တစ်ခုထက်ပိုတဲ့ column တွေကို ရွေးချယ်ပေးတယ်။

In [56]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [59]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [60]:
# Column အများအပြားကို ရွေးချယ်ခြင်း
data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

ဒီလို ပုံစံ indexing လုပ်တာ ချွင်းချက် ရှိတယ်။ 

- slicing ဆိုရင် အဲ့လိုလုပ်တာ column slice မဟုတ်တော့ပဲ row တွေကို slice တယ်။
- Boolean Indexing (filtering)

In [61]:
# Row များကို slicing လုပ်ခြင်း (အဆင်ပြေစေရန် ပြုလုပ်ပေးထားသော syntax ဖြစ်သည်)
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [62]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [63]:
data["three"] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [64]:
# Boolean filtering (column three က 5 ထပ် ကြီးတဲ့ row တွေကိုပဲ ထုတ်ပေးတယ်။)
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [65]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [66]:
data[data < 5] = 0

In [67]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### `loc` နှင့် `iloc` ကို အသုံးပြု၍ DataFrame တွင် Data ရွေးချယ်ခြင်း

Series လိုပဲ DataFrame မှာလည်း label အခြေပြု indexing အတွက် `loc` နဲ့ integer(position) အခြေပြု indexing အတွက် `iloc` ဟူသော အထူး attribute များ ရှိတယ်။ DataFrame က two-dimensional ဖြစ်သောကြောင့် NumPy လို ပုံစံနဲ့ row ကော column ကောကို label သို့မဟုတ် integer သုံးပြီး indexing လုပ်နိုင်တယ်။

အရင် label ကို အသုံးပြုပြီး row တစ်ခုတည်းကို ရွေးချယ်ပုံကို ကြည့်ရအောင်။

In [68]:
# နမူနာ DataFrame တည်ဆောက်ခြင်း
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [69]:
# Label ကိုသုံး၍ row တစ်ခုတည်းကို ရွေးချယ်ခြင်း
# ရလဒ်သည် column label များပါဝင်သော Series တစ်ခု ဖြစ်လာပါမည်။
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [70]:
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

`loc` တွင် row နှင့် column ရွေးချယ်မှုများကို ကော်မာ (comma) ဖြင့် ခွဲခြား၍ တစ်ပြိုင်နက် လုပ်ဆောင်နိုင်ပါသည်။

In [71]:
# Row နှင့် column ကို တွဲဖက်ရွေးချယ်ခြင်း
data.loc["Colorado", "three"]

np.int64(6)

In [72]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [73]:
data.loc[["Colorado", "Utah"], ["two", "three"]]

          two  three
Colorado    5      6
Utah        9     10

ဆက်လက်၍ `iloc` ကို အသုံးပြု၍ integer များဖြင့် အလားတူ ရွေးချယ်မှုများကို လုပ်ဆောင်ကြည့်ပါမည်။

In [74]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [75]:
# Integer position ဖြင့် row တစ်ခုကို ရွေးချယ်ခြင်း
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [76]:
# Integer position စာရင်းဖြင့် row များကို ရွေးချယ်ခြင်း
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

In [77]:
# Row နှင့် column position များကို တွဲဖက်ရွေးချယ်ခြင်း
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [78]:
# Row အများအပြားနှင့် column အများအပြားကို position ဖြင့် ရွေးချယ်ခြင်း
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    4    5
Utah        11    8    9

Indexing attribute နှစ်ခုလုံးသည် single label များအပြင် slices များနှင့်လည်း အလုပ်လုပ်ပါသည်။

In [79]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
# loc ဖြင့် slicing လုပ်ခြင်း
data.loc[:"Utah", "two"]

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [82]:
data.iloc[:, :3]

          one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [83]:
data.iloc[:, :3][data['three'] > 5]

          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [85]:
data.iloc[:, :3][data['three'] > 5].loc["Utah"].loc["two"]

np.int64(9)

> **သတိပြုရန်:** Boolean array များကို `loc` နှင့် တွဲဖက်အသုံးပြုနိုင်သော်လည်း `iloc` နှင့် တွဲဖက်အသုံးပြု၍ မရပါ။

In [88]:
# Boolean array ကို loc ဖြင့် အသုံးပြုခြင်း
data.loc[data.three >= 2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [89]:
data.iloc[data.three >= 2]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

### DataFrame အတွက် Indexing နည်းလမ်းများ

| Type | Notes |
| :--- | :--- |
| **df[column]** | DataFrame မှ column တစ်ခု သို့မဟုတ် အများအပြားကို ရွေးချယ်သည်။ Boolean array ဖြင့် row filter လုပ်ခြင်း၊ slicing လုပ်ခြင်း သို့မဟုတ် Boolean DataFrame ဖြင့် filter လုပ်ခြင်းတို့အတွက် အထူးအသုံးပြုနိုင်သည်။ |
| **df.loc[rows]** | Label ကို အသုံးပြု၍ row တစ်ခု သို့မဟုတ် အများအပြားကို ရွေးချယ်သည်။ |
| **df.loc[:, cols]** | Label ကို အသုံးပြု၍ column တစ်ခု သို့မဟုတ် အများအပြားကို ရွေးချယ်သည်။ |
| **df.loc[rows, cols]** | Label ကို အသုံးပြု၍ row နှင့် column နှစ်မျိုးလုံးကို ရွေးချယ်သည်။ |
| **df.iloc[rows]** | Integer position ကို အသုံးပြု၍ row တစ်ခု သို့မဟုတ် အများအပြားကို ရွေးချယ်သည်။ |
| **df.iloc[:, cols]** | Integer position ကို အသုံးပြု၍ column တစ်ခု သို့မဟုတ် အများအပြားကို ရွေးချယ်သည်။ |
| **df.iloc[rows, cols]** | Integer position ကို အသုံးပြု၍ row နှင့် column နှစ်မျိုးလုံးကို ရွေးချယ်သည်။ |
| **df.at[row, col]** | Row နှင့် column label ကို အသုံးပြု၍ single scalar value တစ်ခုကို ရွေးချယ်သည်။ |
| **df.iat[row, col]** | Row နှင့် column position (integers) ကို အသုံးပြု၍ single scalar value တစ်ခုကို ရွေးချယ်သည်။ |
| **reindex method** | Label များဖြင့် row သို့မဟုတ် column များကို ရွေးချယ်သည်။ |

---

`at` နဲ့ `iat` method က တန်ဖိုး တစ်ခုပဲ ထုတ်ရင် သုံးတယ်။ ပိုမြန်တယ်။

# 4. Arithmetic and Data Alignment (သင်္ချာတွက်ချက်မှုများနှင့် Data index ညှိခြင်း)

In [90]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [91]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [92]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [93]:
# ပေါင်းခြင်းရလဒ်
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [94]:
# df1 တည်ဆောက်ခြင်း
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])

# df2 တည်ဆောက်ခြင်း
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])

In [95]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [96]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [97]:
# DataFrame နှစ်ခုကို ပေါင်းခြင်း
# label ချင်း ထပ်တူမကျသော နေရာများတွင် NaN များ ဖြစ်ပေါ်လာမည်။
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [98]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})

In [99]:
df1

   A
0  1
1  2

In [100]:
df2

   B
0  3
1  4

In [101]:
df1 + df2

    A   B
0 NaN NaN
1 NaN NaN

### Fill values များဖြင့် Arithmetic method များ အသုံးပြုခြင်း (Arithmetic methods with fill values)

In [102]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))

In [103]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))

In [104]:
# df2 ၏ သတ်မှတ်ထားသော နေရာတွင် null တန်ဖိုး သတ်မှတ်ခြင်း
df2.loc[1, "b"] = np.nan

In [105]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [106]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [107]:
# df1 နှင့် df2 ကို ပေါင်းခြင်း
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [109]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
rdiv

In [110]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [112]:
1 / df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
1.div(df1)

In [113]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

### သင်္ချာဆိုင်ရာ method များ (Flexible arithmetic methods)

| Method | Description |
| :--- | :--- |
| **add, radd** | ပေါင်းခြင်း (+) အတွက် method များ |
| **sub, rsub** | နှုတ်ခြင်း (-) အတွက် method များ |
| **div, rdiv** | စားခြင်း (/) အတွက် method များ |
| **floordiv, rfloordiv** | အကြွင်းမဲ့စားခြင်း (//) အတွက် method များ |
| **mul, rmul** | မြှောက်ခြင်း (*) အတွက် method များ |
| **pow, rpow** | ထပ်ညွှန်းတင်ခြင်း (**) အတွက် method များ |

### DataFrame နှင့် Series ကြား လုပ်ဆောင်ချက်များ (Operations between DataFrame and Series)

မတူညီသော dimension များရှိသည့် NumPy array များကဲ့သို့ပင် DataFrame နှင့် Series ကြား သင်္ချာဆိုင်ရာ တွက်ချက်မှုများကိုလည်း သတ်မှတ်ထားပြီး ဖြစ်ပါသည်။ ဦးစွာ စိတ်ဝင်စားဖွယ် ဥပမာတစ်ခုအနေဖြင့် two-dimensional array တစ်ခုနှင့် ၎င်း၏ row တစ်ခုကြား ခြားနားချက်ကို ကြည့်ပါ-

In [114]:
# 3x4 array တစ်ခု တည်ဆောက်ခြင်း
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [115]:
arr[0]

array([0., 1., 2., 3.])

In [116]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
broadcasting

In [117]:
# နမူနာ DataFrame တည်ဆောက်ခြင်း
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [118]:
# ပထမဆုံး row ကို Series အဖြစ် ရယူခြင်း
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [119]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [121]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [120]:
series3 = frame["d"]
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [122]:
frame.sub(series3, axis="index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# 5. Function Application and Mapping (Function များ အသုံးပြုခြင်းနှင့် Mapping လုပ်ခြင်း)

In [123]:
# random standard normal values များဖြင့် DataFrame တည်ဆောက်ခြင်း
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

               b         d         e
Utah    1.022402 -0.305436 -0.415079
Ohio   -1.064707  0.965680 -0.448742
Texas   1.422941 -0.060749 -0.947986
Oregon  0.218128 -0.201577  1.135905

In [124]:
# element-wise အဖြစ် absolute values (အနှုတ်လက္ခဏာဖြုတ်ခြင်း) များ ရယူခြင်း - Vectorization
np.abs(frame)

               b         d         e
Utah    1.022402  0.305436  0.415079
Ohio    1.064707  0.965680  0.448742
Texas   1.422941  0.060749  0.947986
Oregon  0.218128  0.201577  1.135905

In [126]:
frame

               b         d         e
Utah    1.022402 -0.305436 -0.415079
Ohio   -1.064707  0.965680 -0.448742
Texas   1.422941 -0.060749 -0.947986
Oregon  0.218128 -0.201577  1.135905

In [125]:
# Series တစ်ခု၏ maximum နှင့် minimum ခြားနားချက်ကို ရှာသည့် function f1 -> range
def f1(x):
    return x.max() - x.min()

In [127]:
frame.apply(f1)

b    2.487649
d    1.271116
e    2.083891
dtype: float64

In [129]:
frame.apply(f1, axis="columns")

Utah      1.437481
Ohio      2.030388
Texas     2.370927
Oregon    1.337482
dtype: float64

In [130]:
# min နှင့် max တန်ဖိုးနှစ်ခုလုံးကို Series အဖြစ် ပြန်ပေးမည့် function f2
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [132]:
frame.apply(f2, axis="columns")

             min       max
Utah   -0.415079  1.022402
Ohio   -1.064707  0.965680
Texas  -0.947986  1.422941
Oregon -0.201577  1.135905

In [134]:
# ဒသမ ၂ နေရာယူရန် format သတ်မှတ်သည့် function
def my_format(x):
    return f"{x:.2f}"

In [135]:
frame.map(my_format)

            b      d      e
Utah     1.02  -0.31  -0.42
Ohio    -1.06   0.97  -0.45
Texas    1.42  -0.06  -0.95
Oregon   0.22  -0.20   1.14