# Layt Lar Mal မှ အခမဲ့ ပညာဒါန အနေဖြင့် youtube မှာ မျှဝေထားသည့် **'Pandas Sorting and Ranking'** ဗီဒီယိုမှ ဖြစ်သည်။

ဒီ လေ့ကျင့်ခန်းများကို Wes McKinney ၏ **Python for Data Analysis : Data Wrangling with pandas, NumPy & Jupyter** ဆိုသည့် စာအုပ်မှာ ကောက်နှုတ်ဖော်ပြသည်။

---

# 💙 Support our work


ကျွန်တော်တို့ရဲ့ ဒီ video လေးက အနည်းငယ်ဖြစ်ဖြစ် အကူညီဖြစ်တယ်ဆိုရင် ကျွန်တော်တို့အား အောက်ပါ နည်းလမ်းများဖြင့် support ပေးနိုင်ပါသည်။ so

👉 **Video Link:** [https://youtu.be/rdwgJPImrx4]

---

### 🌟 Become a Member
Get **full access** to all our learning materials in:
- 📊 **Data Analysis**
- 🤖 **Machine Learning**
- 🧠 **Deep Learning**
- 📈 **Data Science Projects & Tutorials**

👉 **Join here:** [https://www.facebook.com/story.php?story_fbid=862582666283864&id=100075964145979&mibextid=wwXIfr&rdid=Ex5YjWTXhFO2jTEl]

---

### ☕ Buy Me a Coffee
Your support helps us continue creating **free, high-quality educational content**.

👉 **Support usbuymeacoffee.com/zinmin)pe a Coffee]

---

### 👍 Like · Subscribe · Share
Help us grow by supportinchannels:

- ▶️ **Youtube Link:** www.youtube.com/@laytlarmal 
- **Facebook Page:** https://www.facebook.com/laytlarmal**

Every like, share, and subscription truly means a lot 💫

---

**Thank you for being part of our learning community! 🚀**

# Sorting and Ranking (တန်ဖိုးများ စီခြင်းနှင့် အဆင့်သတ်မှတ်ခြင်း)

## 1. Sorting (ကြီးစဉ်ငယ်လိုက် သို့ ငယ်စဉ်ကြီးလိုက်စီခြင်း)

In [4]:
import numpy as np
import pandas as pd

## 2. အဆင့်သတ်မှတ်ခြင်း (Ranking)

In [29]:
# Series တစ်ခုကို index များရောထွေး၍ တည်ဆောက်ခြင်း
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int32

In [30]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [31]:
obj.sort_index(ascending=False)

d    0
c    3
b    2
a    1
dtype: int32

In [32]:
# DataFrame တစ်ခု တည်ဆောက်ခြင်း
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [33]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [35]:
frame.sort_index(axis="columns", ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

### တန်ဖိုးများအလိုက် စီခြင်း (Sorting by Values)

In [36]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [37]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [38]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [39]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [40]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [42]:
# နမူနာ DataFrame တည်ဆောက်ခြင်း
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [43]:
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [44]:
frame.sort_values("a")

   b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [45]:
frame.sort_values(["a", "b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [47]:
frame.sort_values(["a", "b"]).reset_index(drop=True)

   b  a
0 -3  0
1  4  0
2  2  1
3  7  1

## 2 အဆင့်သတ်မှတ်ခြင်း (Ranking)

In [48]:
# Series တစ်ခု တည်ဆောက်ခြင်း
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [49]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [50]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [51]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [52]:
# DataFrame အသစ်တစ်ခု တည်ဆောက်ခြင်း
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], 
                      "a": [0, 1, 0, 1],
                      "c": [-2, 5, 8, -2.5]})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [53]:
frame.rank()

     b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [54]:
frame.rank(axis="columns")

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0